name: omni_vision
description: 
version: 0.0.2
repository: https://github.com/realmousy/omni_vision.git
homepage: https://github.com/realmousy/omni_vision.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit: ^0.7.2
  tflite: ^1.1.2
  visibility_detector: ^0.2.0
  path_provider: ^2.0.3
  device_info: ^2.0.2
  camera: ^0.9.2+2
  collection: ^1.15.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
