name: omni_vision
description: A new Flutter package project.
version: 0.0.0
repository: https://github.com/realmousy/omni_vision.git
homepage: https://github.com/realmousy/omni_vision.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
